### ISSUE TITLE
Landing Page Grid and Auto Layout (Figma)

### ISSUE THREAD

**Issue by acka47** [hbz/metadaten.nrw#12]
- Container erstellen in Figma
- Sections erstellen bzw. Elemente gruppieren (vgl. Tutorial für Developers)
- Header Marc Text + Graphic in Container
https://www.youtube.com/watch?v=To_ADCVSg5g 
- rem und vs plugins figma
- https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design#using_viewport_units_for_responsive_typography

**Comment by kaena83** [comment]
Irrelevant.
