### ISSUE TITLE
Set up empty Strapi instance

### ISSUE THREAD

**Issue by acka47** [hbz/metadaten.nrw#2]
For Metadaten.nrw (and two additional instances for RPB/hbz website).

**Comment by Phu2** [comment]
Deployed three new instances on the test server using Ansible and Docker:

- strapi-rpb: http://test-metadaten-nrw.hbz-nrw.de:1339/
- strapi-metadaten-nrw: http://test-metadaten-nrw.hbz-nrw.de:1340/
- strapi-hbz: http://test-metadaten-nrw.hbz-nrw.de:1341/

All three are running in `develop` mode.

Content from the old instance were exported and imported into the new instances. The import tool has a bug, see https://github.com/strapi/strapi/issues/15613#issuecomment-1484017837 for workaround.

It seems Strapi doesn't provide a migration tool for sqlite > postgres, so i had to create the admin user manually. An attempt to migrate the databse with `pgloader` did not work out and ended in an unusable postgres database.

**Comment by acka47** [comment]
Es gibt mit den neuen Instanzen Probleme beim Neuanlegen und Löschen von Content Types, die noch behoben werden müssen.

**Comment by acka47** [comment]
Wie gerade im Treffen besprochen:

To Do: 
- [x] Neue, leere Instanzen für RPB und Metadaten.nrw anlegen. 

Die alte Sammelinstanz zum Abgucken aufheben.

**Comment by Phu2** [comment]
Alte Instanz: http://test-metadaten-nrw.hbz-nrw.de:1337/
- mit allen Nutzerkonten
- sqlite-Datenbank

Kopie der alten Instanz mit postgres: http://test-metadaten-nrw.hbz-nrw.de:1338/
- mit neu angelegtem admin user
- postgres-Datenabnk

**Comment by Phu2** [comment]
> Es gibt mit den neuen Instanzen Probleme beim Neuanlegen und Löschen von Content Types, die noch behoben werden müssen.

Sollte jetzt gehen. Ich hatte die Berechtigungen für die Verzeichnisse falsch gesetzt.

**Comment by acka47** [comment]
Closing
