### ISSUE TITLE
Links zu Ressourcen einfügen, die Nutzenden helfen, ihr Arbeitsziel gleich umzusetzen

### ISSUE THREAD

**Issue by kaena83** [hbz/metadaten.nrw#22]
Die Links in der Section "Metadaten, Tools, APIs" führen bisher auf die Produktwebseiten. In machen Fällen könnte es Sinn machen, andere Ressourcen zu verwenden. Z.B. 
"Metadaten in Tools wie OpenRefine nutzen"
- lobid-gnd: https://blog.lobid.org/2018/08/27/openrefine.html
- SkoHub Vocabs: gibt es zu SkoHub Reconcile einen Blogpost? Sonst vielleicht Ankündigung auf Webseite oder Button raus nehmen.

"Metadaten für Datenbanken oder Suchindices beziehen"
- lobid-gnd: https://lobid.org/gnd/api
- lobid-resources: https://lobid.org/resources/api
- lobid-organisations: https://lobid.org/organisations/api/de 

Vielleicht habt ihr noch bessere Ideen.

**Comment by acka47** [comment]
Ich habe versucht, mit [a7fd515](https://github.com/hbz/metadaten.nrw/commit/a7fd5157f5c0af9f1edc9946264e6d9ce8616e77) ein wenig zu verbessern. Prinzipiell bin ich aber nur mit dem Link auf https://lobid.org/gnd/reconcile zufrieden. Für die anderen Anwendungsfälle müssen wir einfach noch entsprechende Einstiegsseiten bauen, sei es auf der jeweiligen Service-Site oder in Strapi...

**Comment by acka47** [comment]
Wir müssen auch noch dran denken, OERSI zu ergänzen.

**Comment by kaena83** [comment]
Für die vollständige Seite "metadaten.nrw" sind Einstiegsseiten für die jeweiligen Anwendungsfälle angedacht. Die Anwendungsfälle und enstprechende Services werden dort im Einzelnen beschrieben. Ressourcen, so wie sie momentan kontextlos verlinkt sind, werden dort als weiterführende Link platziert werden.

**Comment by kaena83** [comment]
Suchindices wie OERSI werden auf einer eigenen Unterseite "Ressourcen finden" verlinkt werden. Dort sollen z.B. auch Suchen von lobid platziert werden.
