### ISSUE TITLE
Deploy page

### ISSUE THREAD

**Issue by sroertgen** [hbz/metadaten.nrw#3]
build is created with `npm run build`

The build directory can then be served with a web server.

@kaena83 can then check the page (can't tag her somehow).

**Comment by dr0i** [comment]
>  (can't tag her somehow).

I've just added  the `offene-infrastruktur` team, of which @kaena83 is a member, with role `write` to https://github.com/hbz/metadaten.nrw/settings/access ->`direct access`.

**Comment by Phu2** [comment]
Deployed with Ansible and Docker on test server: https://stage.metadaten.nrw/
