### ISSUE TITLE
Allgemeinen Einstiegssatz ergänzen

### ISSUE THREAD

**Issue by acka47** [hbz/metadaten.nrw#30]
Wir müssen aufpassen, dass es nicht zuviel Text wird, aber ich denke, wir sollten eine allgemeine Aussage als Einstiegssatz ergänzen. Sowas wie:

> Metadaten.nrw ist ein W egweiser für offene Metadatendienste des Hochschulbibliotheks­ zentrums NRW (hbz).
> Metadaten spielen seit jeher eine zentrale Rolle für die Verwaltung von Ressourcen in Bibliotheken, Archiven und Museen und die wissesnchaftliche Recherche. Ihre Bedeutung in Wissenschaft und Bildung nimmt stetig zu, etwa mit dem Aufbau von Infrastrukturen für Forschungsdaten. Das hbz beteiligt sich auf vielfältige Art und Weise am Aufbau offener Metadateninfrastrukturen – durch Bereitstellung offener und webkonformer Metadaten, Entwicklung und Pflege von Free and Open Source Software (FOSS) und Beteiligung an der community-basierten Entwicklung offener Standards. 
> Mit dieser Webseite laden wir ein, die Angbote des hbz für eine offene Metadatenpraxis zu durchstöbern und näher kennenzulernen!

**Comment by kaena83** [comment]
Ich würde Forschungsdaten dort noch nicht erwähnen, weil es (noch) keine entsprechenden Services gibt. Ansonsten wäre das für den Header zu viel Text, falls das gemeint ist. Aber kann man ja direkt an den Header anschließen.

**Comment by acka47** [comment]
Erledigt.
