### ISSUE TITLE
Kalender-Plugin ausprobieren und Vorschlag machen (Phu)

### ISSUE THREAD

**Issue by sroertgen** [hbz/metadaten.nrw#31]
### Wünsche:

- Aktivierung für alle Kategorien
- Gibt es eine Kalenderansicht aller Termine, die sich filtern lässt?

### Plugin ausprobieren

Das discourse-calender Plugin bietet zwei Möglichkeiten:

1. Ein neues Thema erstellen und dabei einen Kalender einfügen. 

Dieses Thema lässt sich innerhalb einer Kategorie oder global (Kategorien übergreifend) anpinnen. Man kann Einträge zum Kalender hinzufügen, indem man darauf antwortet. https://discourse-test.metadaten.nrw/t/veranstaltungskalender-plugin-ausprobieren/37/6

2. Ein neues Thema erstellen und dabei ein Event erstellen.

Zu einem Event kann man abstimmen/anmelden. Es wird ein gesonderter Kalender "Anstehende Ereignisse" erstellt, der alle **anstehenden** Events enthält. https://discourse-test.metadaten.nrw/upcoming-events

#### Termine über API?

Zu jeder Seite/URL kann man einfach .json dranhängen.
Wir haben u.a. eine Kategorie "Veranstaltungen", in der allgemeine Termine gepostet werden.

https://metadaten.community/c/veranstaltungen/15.json

Darin sind u.a. der `slug` und die `id` der einzelnen Termine enthalten. Damit kann man einen einzelnen Termin abfragen:

https://metadaten.community/t/vbib23-corner-3-metadaten/48.json

und bekommt weitere Details.

Siehe 
https://meta.discourse.org/t/reverse-engineer-the-discourse-api/20576 
https://github.com/discourse/discourse_api

### Vorschlag

- Für allgemeine Termine: 

Kategorie "Veranstaltungen" erstellen. Darin werden Themen/Events anlegt (2.). Dazugehöriger Kalender umbenennen in "Veranstaltungskalender"

Beispiel: https://forum.ansible.com/c/events/8

- Für gruppenspezifische Termine:

Arbeitsgruppen können in ihrer Kategorie einen Kalender erstellen wie in 1. beschrieben.

**Comment by sroertgen** [comment]
Das sieht soweit ganz brauchbar aus. Folgende Attribute brauchen wir im aktuellen Entwurf, die ich noch nicht in der API gesehen habe:

- Ort der Veranstaltung
- Link zu einer Webseite 
- Link zur Registrierung

Kann das Schema der API und entsprechende Felder im Frontend erweitert werden? @Phu2 @acka47

**Comment by Phu2** [comment]
Ich habe gerade in der obigen Beschreibung den Abschnitt "Termine über API?" aktualisiert, @sroertgen. 
Die Links zeigen jetzt auf die Prod-Instanz. Die sind natürlich nicht zugriffsbeschränkt wie bei den vorherigen Test-URLs.
Außerdem der Hinweis, dass bei der Abfrage eines einzelnen Termins man mehr Details bekommt. In dem obigen Beispiel den Link zu einer Webseite, siehe `url` im json. Da gibt es aber keinen Ort und keinen Registrierungs-Link.

Man kann benutzerdefinierte Felder definieren, im json-Output würden sie dann wohl unter `custom_fields` auftauchen.

**Comment by sroertgen** [comment]
Funktioniert soweit für mich und ist prototypisch auf stage implementiert. Was mir noch fehlt:

- Veranstaltungort
- Beschreibung
- Webseite

Das ließe sich ggf. über die `custom_fields` ergänzen.

**Comment by acka47** [comment]
Erledigt, Vorschlag existiert. Ziehen wir glatt, wenn wir im Januar die ersten Realtermine ergänzen.
