### ISSUE TITLE
Delete filters in section metafacture / Praxisbeispiele

### ISSUE THREAD

**Issue by kaena83** [hbz/metadaten.nrw#32]
**Currently**
The filters "metafacture" and "metafacture playground" serve to differentiate between resources referring to either metafacture or metafacture playground.

**Problem**
The resources we have only refer to metafacture, not to metafacture playground. The filters in this section are therefore redundant.

**Required**
Please delete filters in section metafacture / praxisbeispiele.

![grafik](https://github.com/hbz/metadaten.nrw/assets/119848543/ad62eaf9-3d38-4eb4-99b1-60a386dd0773)

**Comment by acka47** [comment]
Erledigt
