### ISSUE TITLE
Align frame in mobile version

### ISSUE THREAD

**Issue by kaena83** [hbz/metadaten.nrw#38]
In mobile view, the right edge of the webpage does not align with the frame of my phone (see screenshot below).

![Image](https://github.com/hbz/metadaten.nrw/assets/119848543/9a846dc0-7752-4347-9db4-0b6688c628fc)

**Comment by sroertgen** [comment]
Sieht in meinem mobile view auf handy und laptop nicht so aus. Ich vermute, dass es der Scrollbar ist. Können wir uns nochmal anschauen

**Comment by kaena83** [comment]
Scheint ein Endgerätproblem zu sein..
